### PR TITLE
Feat/jhipster family/member 8

### PR DESCRIPTION
**Pull request by ascelineboullen**
Add a new artwork to jhipster family: create a Quarkus girl member (requested by @avdev4j 😃 )
Related to https://github.com/jhipster/generator-jhipster/issues/12487

### CODE REVIEW

**Comment by avdev4j** [comment]
Thank you so much @ascelineboullen 

I want to merge it but before I want to be sure we have the rights to use the Quarkus logo.

@joewhite101 @danielpetisme A little gift from Asceline for the Quarkus blueprint !!!

**Comment by danielpetisme** [comment]
So smooth @ascelineboullen!!!! As father of 2 little girls, it means a lot to me to see a girl astronaut, I like it so much, thank you! 
Definitively needs some visibility on social networks as soon as we have the Quarkus logo validation.
@avdev4j did you asked to the Quarkus team ? I can easily get access to couple of them to facilitate, just let me know.

**Comment by avdev4j** [comment]
> Definitively needs some visibility on social networks as soon as we have the Quarkus logo validation.
> @avdev4j did you asked to the Quarkus team ? I can easily get access to couple of them to facilitate, just let me know.

I know you will like it ! :D
TBH I did not ask for the moment, If you have contacts it's probably better if you reached them out. 
Anyway, if the logo is an issue we could just remove it ;).

**Comment by joewhite101** [comment]
I love it! 

@danielpetisme you should reach out. I can do the same to my contacts there. I'm sure it won't be an issue but lets get approval.  Let me know if you want me to follow up as well.

**Comment by danielpetisme** [comment]
I juste posted on Quarkus Zulip
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Logo.20usage.20conditions/near/213080847

I prefer to get a "public" answer.

**Comment by danielpetisme** [comment]
To avoid issues, I think the artwork should include the "The "Q Tracer Path" Element. (ie. the blue Q surrounding the "red-blue" star.
More info
https://quarkus.io/blog/quarkus-has-a-new-logo/

**Comment by pascalgrimaud** [comment]
I don't understand why the target is master instead of main... I'm changing it

**Comment by ascelineboullen** [comment]
@pascalgrimaud I don't understand either, sorry... Thank you! ;)
@danielpetisme, ok I will change the logo this afternoon 👍

**Comment by ascelineboullen** [comment]
@danielpetisme and @avdev4j, it's ok I fixed the logo 😉

**Comment by avdev4j** [comment]
@mraible is it OK from Quarkus to use their logo?

**Comment by joewhite101** [comment]
@avdev4j I'll get sign off. All good for now. I don't expect any issues.

**Pull request merged**
