### PR TITLE
initial move copy of our current artwork to this repo.

### PR DESCRIPTION
**Pull request by atomfrede**
All our current artwork with sources is now in this repository. I added the src files for the stickers I order from time to time (with text underneath).

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @atomfrede - I'm first putting the new artwork here, and the older one might go to an "archive" folder afterwards

**Comment by deepu105** [comment]
@jdubois we could keep the old logos as well, since it will give 2 more variations on top of these. Or atleast the new logo done recently with a different guy. WDYT?

**Comment by jdubois** [comment]
Yes but I'm not sure for the licenses of both older logos, so I don't think we should mix them - or at least put them in an "archive" directory with a clear warning

**Comment by atomfrede** [comment]
Let's close this. I will try to create new wallpapers with the new family members.

**Pull request closed without merging**
