### PR TITLE
Yellow vest edition of a JHipster family member

### PR DESCRIPTION
**Pull request by bnjdpn**
In order to follow Notepad++ with the [Yellow Vest Edition](https://notepad-plus-plus.org/news/notepad-7.6.2-released.html), I thought it would be a good idea to do the same with the famous JHipster family member.

For the moment, I only edited the first one, but I can do the others members of the family.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
-1 from me, too

**Comment by deepu105** [comment]
-1 from me too, as we are a tech stack and not here to make any political
statement

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Closing this as this does not respect the code of conduct or the "welcoming" spirit of the project.

**Comment by PierreBesson** [comment]
-1 I also think that this is too controversial to be included as our artwork. 

However @bnjdpn, as the jhipster artworks are open source under the Apache2 license you are free to create any remix you want as long as you respect the terms of the license. What you must not do in any case is claiming or making people believe that the JHipster project endorses your logo.

**Pull request closed without merging**
