### PR TITLE
Add Micronaut Hipster

### PR DESCRIPTION
**Pull request by wiesej**

### CODE REVIEW

**Comment by jdubois** [comment]
That's awesome, thank you!!!

**Comment by PierreBesson** [comment]
Wait ! I know this is merged but I am afraid it is going to cause a licensing issue because it includes the Micronaut logo.
From https://micronaut.io/faq.html
 
>I see the Micronaut name is trademarked, does that mean it’s proprietary?
>Not at all, the Micronaut name is a trademark of OCI but this does not affect your rights to use and modify the source code under the terms of the Apache License v2.

The name Micronaut is under trademark so we can't use it in our own visuals this would be appropriation.
As for the logo, it might not be under a license that would grant it inclusion in this repo (apache 2).

@jdubois We had the same discussion about the previous JHipster logo which included the angular and spring logo and decided to remove those from the current visuals.

**Comment by mraible** [comment]
The company that created Micronaut also created the logo. So hopefully this isn't an issue.

**Comment by jdubois** [comment]
@PierreBesson yes we also have this issue with the Java logo...
As long as it's commited by someone from the company, who signs the CLA, this should be fine - but to be sure maybe @wiesej you could give an official confirmation from OCI?

**Comment by PierreBesson** [comment]
The concerns have been addressed in an official letter published on a [post in our mailing list](https://groups.google.com/g/jhipster-dev/c/YlAuDhJP6D8/m/2OFsEIR_CwAJ).

Thanks a lot to the Micronaut team at Object Computing, Inc.

**Pull request merged**
