### PR TITLE
Add JHipster Lite Logos

### PR DESCRIPTION
**Pull request by sabrinapayet**
JHipster-Lite-neon-green

JHipster-Lite-neon-pink

JHipster-Lite-neon-yellow

JHipster-Lite-neon-blue

Related to https://github.com/jhipster/jhipster-lite/issues/347
As asked by @pascalgrimaud

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks a lot for your work @sabrinapayet 
These logos are important, because the current one is not accessible at all, when changing appearance and using dark mode.

**Comment by pascalgrimaud** [comment]
We should update our current logo too, as it's not nice with dark mode:

image

What do you think @jdubois ?

**Comment by jdubois** [comment]
Yes the blue one is very cool (I'm keeping blue as it's our usual color).
Great work @sabrinapayet !

**Comment by pascalgrimaud** [comment]
Yes, I'll use the neon blue for JHipster Lite.

Then, for classic JHipster, it can be done in another ticket, without the "lite" word

**Comment by sabrinapayet** [comment]
Thank you. I'll finish the classic JHipster logo this week to make it accessible too.

**Pull request merged**
