### PR TITLE
Create new member for jhipster family. Add png and svg formats

### PR DESCRIPTION
**Pull request by ascelineboullen**
I create a new member for Jhipster family. Add png and svg formats.
I'm assigned on this issue : https://github.com/jhipster/generator-jhipster/issues/12487#issuecomment-705387639

### CODE REVIEW

**Comment by deepu105** [comment]
Thank you so much @ascelineboullen its awesome

**Review by deepu105 — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@ascelineboullen : for your information, I just changed the default branch from master to main. Don't hesitate to tell me if you encounter some issue

**Comment by avdev4j** [comment]
I've added the hacktoberfest label after the pr has been merged, I hope it will works.

@pascalgrimaud @deepu105 maybe it's better to add the directly the topic.

**Comment by pascalgrimaud** [comment]
done

**Comment by avdev4j** [comment]
Thanks you mate

**Pull request merged**
